Update Safe Dependencies
cowprotocol/solver-rewards pull request #309
Opened 2023-07-04 09:24 UTC by bh2smith

Recently Safe Team officially dropped support for the transaction service urls [referencing gnosis](https://github.com/5afe/safe-cli/commit/8522b5b559c6d274bb77d651d365cb5c4391951f) so we had to update our packages. This came along with a chain reaction of package updates. I tried to keep them as minimal as possible.

Note that there was a mypy error that had to be ignored.

2023-07-04 15:28 UTC, gentrexha requested changes
There's an instance of `toChecksumAddress` inside of the test class`TestTransactionPost` inside of `test_post_transaction.py`. Are we not running e2e tests as part of the CI-CD pipeline?

2023-07-04 15:28 UTC, gentrexha commented on src/multisend.py
> +    eth_balance = client.get_balance(web3.to_checksum_address(safe_address))
This should be already a `web3.to_checksum_address(safe_address)` returned object, no? Since we're already applying that function inside of `constants.py`. What do you think?

2023-07-05 08:17 UTC, bh2smith commented on src/multisend.py
> +    eth_balance = client.get_balance(web3.to_checksum_address(safe_address))
Yea, perhaps, I will try and remove it and see how it goes.

2023-07-05 12:37 UTC, bh2smith commented on src/multisend.py
> +    eth_balance = client.get_balance(web3.to_checksum_address(safe_address))
was not necessary

2023-07-05 12:37 UTC, bh2smith commented on src/multisend.py
> +    eth_balance = client.get_balance(web3.to_checksum_address(safe_address))
```suggestion
    eth_balance = client.get_balance(safe_address)
```

2023-07-05 12:40 UTC, bh2smith commented
Thanks @gentrexha -- I have found and fixed the things pointed out.

2023-07-05 12:43 UTC, bh2smith commented on src/multisend.py
> +    safe_address: ChecksumAddress,
Note that this was the reason for the apparently unnecessary `to_checksum_address` commented [here](https://github.com/cowprotocol/solver-rewards/pull/309#discussion_r1252065532)

2023-07-05 12:43 UTC, bh2smith commented on src/multisend.py
> +    eth_balance = client.get_balance(web3.to_checksum_address(safe_address))
Fixed over here:

https://github.com/cowprotocol/solver-rewards/pull/309/files#r1253052954

2023-07-05 14:27 UTC, gentrexha approved these changes

2023-07-05 14:31 UTC, merged