Implementation of CIP-38
cowprotocol/solver-rewards pull request #345
Opened 2024-03-05 12:39 UTC by fhenneke

This PR implements changes to solver rewards scripts for CIP-38 on ranking by surplus.

The main change is that rewards are computed based on surplus (and protocol fees) and not based on surplus and network fees (and protocol fees). Additionally, there is no cost reimbursement but the slippage computation includes a contribution from fees.

The implementation in this PR is quite minimal.
The batch rewards query ignores network fees for payment but explicitly returns aggregated network fees to add them to slippage. The other changes are only slight renames (e.g. 
 from `payment_eth` to `primary_reward_eth`). Test have been adapted accordingly.
The slippage query does not change. Instead, when generating the final merged dataframe, network fees are explicitly added to slippage. Test have been adapted and a few comments were added.

A few things can be implemented differently:
- Instead of computing payments from surplus and protocol fees, one could have used `winning_score`. This is a bit simpler but would require checking somewhere that the score is consistent with the on-chain settlement.
- The slippage computation could have been adapted to not exclude network fees and use external prices for converting those fees to ETH. This would require uploading explicit information on fees and their native prices to dune. This should be done at some point, but maybe not for the release.

The changes to computing rewards in `batch_rewards.sql` need to be ported to dune-sync.

2024-03-06 16:29 UTC, harisang commented on src/fetch/payouts.py
> +    "primary_reward_eth",
Is the plan that network fees do not appear here? Are they supposed to be part of slippage?

2024-03-06 16:47 UTC, harisang commented on src/fetch/payouts.py
> +        assert quote_reward_cow >= 0, "invalid secondary_reward_cow"
```suggestion
        assert quote_reward_cow >= 0, "invalid quote_reward_cow"
```

2024-03-06 16:48 UTC, harisang commented on src/fetch/payouts.py
> +    "primary_reward_eth",
As a side note, it would be good to add a comment here describing what each column is meant to be.

2024-03-06 23:43 UTC, harisang commented
Should we try to remove unnecessary parts of the query? One thing that comes to mind is carrying around `execution_cost `although never needing it.

2024-03-06 23:43 UTC, harisang requested changes
Added a few comments

2024-03-07 09:29 UTC, fhenneke commented on src/fetch/payouts.py
> +    "primary_reward_eth",
I am not sure what the best implementation is here. I would like to move network fees completely into slippage. But the simplest approach is to not change the slippage query and instead use network fees as computed in batch rewards. This is a bit indirect and potentially hard to maintain. It should be fine if we intend to rework slippage anyways.

The dataframes here might still contain columns for network fees, so adding those here should probably be done.

2024-03-07 09:33 UTC, fhenneke commented
> Should we try to remove unnecessary parts of the query? One thing that comes to mind is carrying around `execution_cost `although never needing it.

I thought about removing lots of stuff from the batch rewards query. I did not do it because I want to use a copy (of the first part of) the query without changes.We might want to sync more data on dune.

2024-03-07 15:55 UTC, harisang commented
I ran the script locally and it crushed in this line.
https://github.com/cowprotocol/solver-rewards/blob/4f101e933b4c710ebb4ce6f2edd83e05193b4b4f/src/fetch/payouts.py#L420

I suspect we need to rename `reward_cow` to `primary_reward_cow`

2024-03-21 15:26 UTC, harisang approved these changes
Looks good.

2024-03-21 15:27 UTC, harisang commented
@fhenneke Have you done a dry run to double-check that results make sense?

2024-03-25 00:31 UTC, merged