Add batch and order data jobs
cowprotocol/solver-rewards pull request #448
Opened 2024-12-06 23:15 UTC by harisang

This PR adds some functionality that is disjoint from the rest of the payouts script, and can be used to set up a cronjob that sync some batch and order data to the analytics db.

2024-12-09 10:56 UTC, fhenneke requested changes
It seems that you want to merge the solver rewards code with the dune sync code. That would require some code restructuring to make the code consistent. Or massive clanup if merged in a state close to the current state of the PR.

Is the long term plan to make this repo into a solver-accounting repo? Would all code have to be compatible or should it be separate folders with independent code?

2024-12-09 10:56 UTC, fhenneke commented on src/dbt/__init__.py
The folder name dbt is a bit confusing. I guess it is meant as a placeholder for the actual dbt stuff. But for the foreseeable future, it should be named something like `data_sync`.

2024-12-09 10:56 UTC, fhenneke commented on src/dbt/config.py
> +from __future__ import annotations
This does not look like it is required.

2024-12-09 10:56 UTC, fhenneke commented on src/models/block_range.py
> +        ]
Is this function being used?

2024-12-09 10:56 UTC, fhenneke commented on src/fetch/orderbook.py
> +"""Basic client for connecting to postgres database with login credentials"""
If we really want to merge the two codebases, this needs to be combined with `pg_client.py`.

2024-12-09 10:56 UTC, fhenneke commented on src/fetch/orderbook.py
> +        epsilon_upper = str(os.environ[f"EPSILON_UPPER_{network}"])
If we really want to merge these code bases, this should probably use the config object.

2024-12-09 10:56 UTC, fhenneke commented on src/dbt/common.py
> +    """
This function might benefit from documenting the return value in a bit more detail.

2024-12-09 10:56 UTC, fhenneke commented on src/dbt/sync_data.py
> +        end_block = block_range_list[i][1]
```suggestion
    for i, (start_block, end_block) in enumerate(block_range_list):
```

2024-12-09 10:56 UTC, fhenneke commented on src/dbt/sync_data.py
> +        end_block = block_range_list[i][1]
Or better yet, zip all those lists and avoid the index `i`.

2024-12-09 10:56 UTC, fhenneke commented on src/fetch/orderbook.py
> +        return create_engine(db_string)
```suggestion
        if db_env == OrderbookEnv.ANALYTICS:
            db_url = os.environ["ANALYTICS_DB_URL"]
        else:
            db_url = os.environ[f"{db_env}_DB_URL"]

        db_string = f"postgresql+psycopg2://{db_url}"
        return create_engine(db_string)
```
would be easier for me to parse

2024-12-09 11:51 UTC, harisang commented on src/models/block_range.py
> +        ]
Good point. removed

2024-12-09 11:51 UTC, harisang commented on src/dbt/config.py
> +from __future__ import annotations
Removed

2024-12-11 09:50 UTC, harisang commented
So some code is currently commented out; it is meant to do proper type casting but doesn't work as expected. It is also not clear if type casting is really needed so will investigate further.

For now, i am creating a tag from this branch so that we can proceed with a test deployment

2024-12-11 22:59 UTC, fhenneke reviewed
I checked the logic of `get_batch_data` and it looks fine.

2024-12-11 22:59 UTC, fhenneke commented on src/fetch/orderbook.py
> +        load_dotenv()
Is this still needed?

2024-12-11 22:59 UTC, fhenneke commented on src/fetch/orderbook.py
> +        Decomposes the block range into buckets of 10k blocks each,
Concrete bucket size is outdated.

2024-12-11 22:59 UTC, fhenneke commented on src/fetch/orderbook.py
> +            size = min(end - start + 1, bucket_size)
Checked the `+1`s and `-1`s and they look correct.

2024-12-11 22:59 UTC, fhenneke commented on queries/orderbook/order_data.sql
> +    '{{env}}' as environment,
Looks like a good idea!

2024-12-11 22:59 UTC, fhenneke commented on src/fetch/orderbook.py
> +        return pd.concat(res)
I know that this is not horrible code duplication. Not many lines can be saved by moving the chunking into its own function and one would have to awkwardly pass a function as argument to it.
But then again the logic of chunking always has potential for off by one errors. So I would still think it is worth it to refactor this at some point into one function for chunking which then can also be properly tested.

2024-12-11 22:59 UTC, fhenneke commented on src/fetch/orderbook.py
> +            .replace("{{results}}", "dune_sync_batch_data_table")
Is it possible to also add an `{{env}}` to the batch rewards query?

2024-12-12 01:58 UTC, harisang commented on src/fetch/orderbook.py
> +        load_dotenv()
Removed

2024-12-13 16:41 UTC, fhenneke approved these changes

2024-12-13 16:42 UTC, merged