Add more info in slack message
cowprotocol/solver-rewards pull request #475
Opened 2024-12-24 15:52 UTC by harisang

This PR adds a bit more info in the final logging messages.

~~PR #474 needs to be merged first, so marking as draft for now~~

This PR addresses issue #472

2025-01-02 13:48 UTC, fhenneke commented on src/fetch/transfer_file.py
> +    network = Network(os.environ["NETWORK"])
The network should be made part of the config, e.g., an attribute of `AccountingConfig`.

2025-01-02 13:51 UTC, fhenneke requested changes
I would like us to stick to the convention to pass all config via the `AccountingConfig` object.

2025-01-09 16:15 UTC, harisang commented on src/fetch/transfer_file.py
> +    network = Network(os.environ["NETWORK"])
Ended up using the `config.dune_config.dune_blockchain` parameter, as suggested in another PR

2025-01-10 11:24 UTC, fhenneke approved these changes

2025-01-10 15:28 UTC, merged